# Generated by Django 2.2 on 2023-09-29 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='NAME')),
                ('dob', models.DateField(verbose_name='DOB')),
                ('address', models.TextField(verbose_name='ADDRESS')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', message="Phone number must be in the format: '9999999999'")])),
                ('email', models.EmailField(max_length=254, verbose_name='E_MAIL')),
                ('program', models.CharField(max_length=25, verbose_name='PROGRAM NAME')),
                ('department', models.CharField(max_length=25, verbose_name='DEPARTMENT NAME')),
                ('job_title', models.CharField(max_length=25, verbose_name='JOB TITLE')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
    ]
