# Generated by Django 2.2 on 2023-10-23 07:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import libraryapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_auto_20231011_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('des_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Designation Id')),
                ('designation', models.CharField(max_length=50, verbose_name='Designation')),
            ],
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='phone_number',
            field=models.CharField(default='+91', max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must start with '+91' followed by 10 digits.", regex='^\\+91\\d{10}$'), libraryapp.models.validate_phone_number], verbose_name='Phone Number'),
        ),
        migrations.CreateModel(
            name='Staffreg',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Staff Id')),
                ('staff_name', models.CharField(max_length=25, verbose_name='Staff Name')),
                ('dob', models.DateField(validators=[libraryapp.models.validate_age_staff], verbose_name='Date Of Birth')),
                ('address', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\s]*$', message='Address should start with a capital letter')], verbose_name='Address')),
                ('phone_number', models.CharField(default='+91', max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must start with '+91' followed by 10 digits.", regex='^\\+91\\d{10}$'), libraryapp.models.validate_phone_number], verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid email format.')], verbose_name='Email')),
                ('pwd', models.CharField(default='L2V42232XZeI', editable=False, max_length=25, verbose_name='Password')),
                ('pic', models.ImageField(upload_to='staff_images/', validators=[libraryapp.models.validate_image_extension], verbose_name='Profile Picture')),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Department')),
                ('des_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Designation')),
            ],
        ),
    ]
