# Generated by Django 2.2 on 2023-10-23 12:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import libraryapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_auto_20231023_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='d_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='designation',
            name='des_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='program',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid Email Format')], verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='pwd',
            field=models.CharField(default='AU2r7SE9i9cG', editable=False, max_length=25, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='address',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\s]*$', message='Address should start with a capital letter')]),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='dob',
            field=models.DateField(validators=[libraryapp.models.validate_age]),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid email format.')]),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='phone_number',
            field=models.CharField(default='+91', max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must start with '+91' followed by 10 digits.", regex='^\\+91\\d{10}$'), libraryapp.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='pwd',
            field=models.CharField(max_length=25, validators=[libraryapp.models.validate_password, django.core.validators.RegexValidator(message='Password must be at least 8 characters long.', regex='^.{8,}$')]),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='student_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\s]*$', message='Name should start with a capital letter')]),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('d_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryapp.Department')),
                ('des_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryapp.Designation')),
                ('p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryapp.Program')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
            },
        ),
    ]
