# Generated by Django 2.2 on 2023-10-23 13:30

from django.db import migrations, models
import libraryapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_auto_20231023_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreg',
            name='pwd',
            field=models.CharField(default='4xpfCNPROM2c', editable=False, max_length=25, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='dob',
            field=models.DateField(blank=True, null=True, validators=[libraryapp.models.validate_age], verbose_name='Date Of Birth'),
        ),
    ]
