# Generated by Django 2.2 on 2023-10-23 13:32

from django.db import migrations, models
import libraryapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_auto_20231023_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreg',
            name='dob',
            field=models.DateField(blank=True, null=True, validators=[libraryapp.models.validate_age_staff], verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='pwd',
            field=models.CharField(default='hDjJ2fcxIQZH', editable=False, max_length=25, verbose_name='Password'),
        ),
    ]
