# Generated by Django 2.2 on 2023-10-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_auto_20231023_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreg',
            name='pwd',
            field=models.CharField(default='valioHeeteN5', max_length=25, verbose_name='Password'),
        ),
    ]
