# Generated by Django 2.2 on 2023-10-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_auto_20231023_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='pwd',
            field=models.CharField(default='dcGXcQFKCv5b', max_length=25, verbose_name='Password'),
        ),
    ]
