# Generated by Django 2.2 on 2023-10-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0008_auto_20231023_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='designation',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='pwd',
            field=models.CharField(default='Ir1SEIaQdn3u', max_length=25, verbose_name='Password'),
        ),
    ]
