# Generated by Django 2.2 on 2023-10-28 18:23

import django.core.validators
from django.db import migrations, models
import libraryapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_auto_20231024_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreg',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid Email Format'), django.core.validators.RegexValidator(message="Invalid email domain. Use '@amaljyothi.ac.in'.", regex='@amaljyothi\\.ac\\.in$')]),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='phone_number',
            field=models.CharField(blank=True, default='+91', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must start with '+91' followed by 10 digits.", regex='^\\+91\\d{10}$'), libraryapp.models.validate_phone_number], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='pwd',
            field=models.CharField(default='uX4RXcTTlKKM', max_length=25, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid email format.'), django.core.validators.RegexValidator(message="Invalid email domain. Use '@mca.ajce.in', '@intmca.ajce.in', or '@cs.ajce.in'.", regex='@(?:mca\\.ajce\\.in|intmca\\.ajce\\.in|cs\\.ajce\\.in)$')]),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='phone_number',
            field=models.CharField(blank=True, default='+91', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must start with '+91' followed by 10 digits.", regex='^\\+91\\d{10}$'), libraryapp.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='pwd',
            field=models.CharField(default='jivQj42dd8SR', max_length=25, verbose_name='Password'),
        ),
    ]
