# Generated by Django 2.2 on 2023-10-30 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0011_auto_20231030_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='type_of_book',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('Biography', 'Biography'), ('Computer Science', 'Computer Science')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='pwd',
            field=models.CharField(default='1t6kCgZbyvki', max_length=25, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='pwd',
            field=models.CharField(default='F48SIylTDNqv', max_length=25, verbose_name='Password'),
        ),
    ]
