# Generated by Django 2.2 on 2023-10-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0012_auto_20231030_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreg',
            name='pwd',
            field=models.CharField(default='uE4o3gVBFB8a', max_length=25, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='pwd',
            field=models.CharField(default='sfwB0aLyk9DF', max_length=25, verbose_name='Password'),
        ),
    ]
