# Generated by Django 2.2 on 2023-10-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0014_auto_20231031_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreg',
            name='pwd',
            field=models.CharField(default='ZHhd9DeLkk1Z', max_length=25, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='pwd',
            field=models.CharField(default='U5130PwlXMqz', max_length=25, verbose_name='Password'),
        ),
    ]
