# Generated by Django 2.2 on 2023-10-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0015_auto_20231031_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreg',
            name='pwd',
            field=models.CharField(default='IUSG7UJloZy1', max_length=25, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='pwd',
            field=models.CharField(default='XzrRW60WsTtR', max_length=25, verbose_name='Password'),
        ),
    ]
