# Generated by Django 2.2 on 2023-11-01 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0017_auto_20231101_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreg',
            name='libno',
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='pwd',
            field=models.CharField(default='Xbx1Imzc3InZ', max_length=25, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='d_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Department'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='p_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Program'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='pwd',
            field=models.CharField(default='jzKZBxy5xTKR', max_length=25, verbose_name='Password'),
        ),
    ]
