# Generated by Django 2.2 on 2023-11-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0018_auto_20231101_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreg',
            name='d_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Department'),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='des_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Designation'),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='pwd',
            field=models.CharField(default='rklzyXjzt3Wh', max_length=25, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='staff_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Staff Id'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='pwd',
            field=models.CharField(default='DHu0fy3JK6jj', max_length=25, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='student_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
