# Generated by Django 2.2 on 2023-11-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0022_auto_20231106_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreg',
            name='pwd',
            field=models.CharField(default='yBeVJ0UkSO99', max_length=25, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='pwd',
            field=models.CharField(default='LGLpURbBXwXK', max_length=25, verbose_name='Password'),
        ),
    ]
